import Head from "next/head";
import Image from "next/image";
import { LogoNav } from "../components/LogoNav";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by Sayroback" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LogoNav />
    </div>
  );
}
